org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.231
neo_version_range=[21.1,)
loader_version_range=[4,)

mod_id=lets_do_create_compat
mod_name=Let's Do Create Compat
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.angryjoe.letsdocreatecompat
